configured_endpoints: 17
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/groqcloud%2Fgroqcloud-321ea3c10bc0eb2b17407a99eb47e8ea88e67bf7bff8bebe3592fbd4f73b1f89.yml
openapi_spec_hash: d0f5f934d8a12f79db0cbdb7b6b3d0e3
config_hash: 6b1c374dcc1ffa3165dd22f52a77ff89
