configured_endpoints: 17
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/groqcloud%2Fgroqcloud-538b507a2769cb4ff3d4eb53d10edf7bf0c0b9adc454afc10a8bf8db68509b8f.yml
openapi_spec_hash: 8a5a5a4f99714bce1b6ec8db313ccfb7
config_hash: 6b1c374dcc1ffa3165dd22f52a77ff89
